name: 'Install Github Package using Yarn'
author: aspecto-io
description: 'Create required npmrc, run yarn and delete npmrc.'
inputs:
  token:
    description: 'Github Personal Access Token with read:packages scope'
    required: true
  registry:
    description: 'Name of the github registry'
    required: true

runs:
  using: 'composite'
  steps:
    - run: echo "Creating .npmrc"
      shell: bash
    - run: echo "@${{ inputs.registry }}:registry=https://npm.pkg.github.com" >> ~/.npmrc
      shell: bash
    - run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.token }}" >> ~/.npmrc
      shell: bash
    - run: cat ~/.npmrc
      shell: bash
    - run: echo "Installing"
      shell: bash
    - run: yarn
      shell: bash
    - run: echo "Removing .npmrc"
      shell: bash
    - run: rm ~/.npmrc
      shell: bash
branding:
  icon: package
  color: orange
  